# Generated by Django 5.0.6 on 2024-07-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="photo_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
