# Generated by Django 5.0.6 on 2024-07-10 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0002_user_photo_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="middle_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name="BankDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank", models.CharField(max_length=100)),
                ("ifsc_code", models.CharField(max_length=11, unique=True)),
                ("account_number", models.CharField(max_length=20)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("SB", "Savings"),
                            ("CB", "Current"),
                            ("NE", "NRE"),
                            ("NO", "NRO"),
                        ],
                        default="SB",
                        max_length=2,
                    ),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bankdetail",
                        related_query_name="bankdetail",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KycDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pan", models.CharField(blank=True, max_length=10)),
                (
                    "tax_status",
                    models.CharField(blank=True, default="01", max_length=2),
                ),
                (
                    "occ_code",
                    models.CharField(
                        blank=True,
                        choices=[("01", "Business"), ("02", "Services")],
                        default="02",
                        max_length=2,
                    ),
                ),
                ("dob", models.CharField(blank=True, max_length=10)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female")],
                        max_length=2,
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        help_text="sample: 10, Mg Road, New Delhi - 11001",
                        max_length=120,
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=35)),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AN", "Andaman & Nicobar"),
                            ("AR", "Arunachal Pradesh"),
                            ("AP", "Andhra Pradesh"),
                            ("AS", "Assam"),
                            ("BH", "Bihar"),
                            ("CH", "Chandigarh"),
                            ("CG", "Chhattisgarh"),
                            ("DL", "Delhi"),
                            ("GO", "GOA"),
                            ("GU", "Gujarat"),
                            ("HA", "Haryana"),
                            ("HP", "Himachal Pradesh"),
                            ("JM", "Jammu & Kashmir"),
                            ("JK", "Jharkhand"),
                            ("KA", "Karnataka"),
                            ("KE", "Kerala"),
                            ("MP", "Madhya Pradesh"),
                            ("MA", "Maharashtra"),
                            ("MN", "Manipur"),
                            ("ME", "Meghalaya"),
                            ("MI", "Mizoram"),
                            ("NA", "Nagaland"),
                            ("ND", "New Delhi"),
                            ("OR", "Orissa"),
                            ("PO", "Pondicherry"),
                            ("PU", "Punjab"),
                            ("RA", "Rajasthan"),
                            ("SI", "Sikkim"),
                            ("TG", "Telengana"),
                            ("TN", "Tamil Nadu"),
                            ("TR", "Tripura"),
                            ("UP", "Uttar Pradesh"),
                            ("UC", "Uttaranchal"),
                            ("WB", "West Bengal"),
                            ("DN", "Dadra and Nagar Haveli"),
                            ("DD", "Daman and Diu"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "pincode",
                    models.CharField(
                        blank=True, help_text="sample: 110049", max_length=6
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="sample: 9999999999", max_length=10
                    ),
                ),
                ("paperless_flag", models.CharField(max_length=1)),
                (
                    "nominee_name",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("ckyc_number", models.CharField(blank=True, max_length=14, null=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="kycdetail",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
