# Generated by Django 5.0.6 on 2024-07-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0003_user_middle_name_bankdetail_kycdetail"),
    ]

    operations = [
        migrations.AddField(
            model_name="kycdetail",
            name="kyc_type",
            field=models.CharField(default="abc", max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kycdetail",
            name="nominee_relation",
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
