# Generated by Django 5.0.6 on 2024-07-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0004_kycdetail_kyc_type_kycdetail_nominee_relation"),
    ]

    operations = [
        migrations.AddField(
            model_name="kycdetail",
            name="country",
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
