# Generated by Django 5.0.6 on 2024-07-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0006_alter_bankdetail_ifsc_code_alter_user_middle_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="MutualFundList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unique_no", models.IntegerField()),
                ("scheme_code", models.CharField(max_length=10)),
                ("rta_scheme_code", models.CharField(max_length=10)),
                ("amc_scheme_code", models.CharField(max_length=10)),
                ("isin", models.CharField(max_length=12)),
                ("amc_code", models.CharField(max_length=50)),
                ("scheme_type", models.CharField(max_length=20)),
                ("scheme_plan", models.CharField(max_length=20)),
                ("scheme_name", models.CharField(max_length=200)),
                ("purchase_allowed", models.CharField(max_length=1)),
                ("purchase_transaction_mode", models.CharField(max_length=5)),
                (
                    "minimum_purchase_amount",
                    models.DecimalField(decimal_places=3, max_digits=10),
                ),
                (
                    "additional_purchase_amount",
                    models.DecimalField(decimal_places=3, max_digits=10),
                ),
                (
                    "maximum_purchase_amount",
                    models.DecimalField(decimal_places=3, max_digits=10),
                ),
                (
                    "purchase_amount_multiplier",
                    models.DecimalField(decimal_places=3, max_digits=5),
                ),
                ("purchase_cutoff_time", models.TimeField()),
                ("redemption_allowed", models.CharField(max_length=1)),
                ("redemption_transaction_mode", models.CharField(max_length=5)),
                (
                    "minimum_redemption_qty",
                    models.DecimalField(decimal_places=3, max_digits=5),
                ),
                (
                    "redemption_qty_multiplier",
                    models.DecimalField(decimal_places=3, max_digits=5),
                ),
                (
                    "maximum_redemption_qty",
                    models.DecimalField(decimal_places=3, max_digits=5),
                ),
                (
                    "redemption_amount_minimum",
                    models.DecimalField(decimal_places=3, max_digits=5),
                ),
                (
                    "redemption_amount_maximum",
                    models.DecimalField(decimal_places=3, max_digits=5),
                ),
                (
                    "redemption_amount_multiple",
                    models.DecimalField(decimal_places=3, max_digits=5),
                ),
                ("redemption_cutoff_time", models.TimeField()),
                ("rta_agent_code", models.CharField(max_length=10)),
                ("amc_active_flag", models.IntegerField()),
                ("dividend_reinvestment_flag", models.CharField(max_length=1)),
                ("sip_flag", models.CharField(max_length=1)),
                ("stp_flag", models.CharField(max_length=1)),
                ("swp_flag", models.CharField(max_length=1)),
                ("switch_flag", models.CharField(max_length=1)),
                ("settlement_type", models.CharField(max_length=5)),
                ("amc_ind", models.CharField(blank=True, max_length=10)),
                ("face_value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("exit_load_flag", models.CharField(max_length=1)),
                ("exit_load", models.IntegerField()),
                ("lock_in_period_flag", models.CharField(max_length=1)),
                ("lock_in_period", models.IntegerField()),
                ("channel_partner_code", models.CharField(max_length=10)),
                ("reopening_date", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
