# Generated by Django 5.0.6 on 2024-07-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0007_mutualfundlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mutualfundlist",
            name="additional_purchase_amount",
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="mutualfundlist",
            name="amc_active_flag",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="mutualfundlist",
            name="exit_load",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="mutualfundlist",
            name="face_value",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="mutualfundlist",
            name="lock_in_period",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="mutualfundlist",
            name="maximum_purchase_amount",
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="mutualfundlist",
            name="maximum_redemption_qty",
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name="mutualfundlist",
            name="minimum_purchase_amount",
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="mutualfundlist",
            name="minimum_redemption_qty",
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name="mutualfundlist",
            name="purchase_amount_multiplier",
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name="mutualfundlist",
            name="purchase_cutoff_time",
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name="mutualfundlist",
            name="redemption_amount_maximum",
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name="mutualfundlist",
            name="redemption_amount_minimum",
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name="mutualfundlist",
            name="redemption_amount_multiple",
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name="mutualfundlist",
            name="redemption_cutoff_time",
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name="mutualfundlist",
            name="redemption_qty_multiplier",
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
    ]
