# Generated by Django 5.0.6 on 2024-07-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0011_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="kycdetail",
            name="client_code",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
