# Generated by Django 5.0.6 on 2024-07-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0013_alter_transaction_transaction_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="order_id",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
