# Generated by Django 5.0.6 on 2024-07-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0014_transaction_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="bse_trans_no",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="order_id",
            field=models.CharField(max_length=20),
        ),
    ]
