# Generated by Django 5.0.6 on 2024-07-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0015_alter_transaction_bse_trans_no_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="return_grade",
            field=models.CharField(max_length=200),
        ),
    ]
