# Generated by Django 5.0.6 on 2024-07-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0016_alter_transaction_return_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="kycdetail",
            name="income_slab",
            field=models.CharField(
                choices=[
                    ("31", "Below 1 Lakh"),
                    ("32", "> 1 <=5 Lacs"),
                    ("33", ">5 <=10 Lacs"),
                    ("34", ">10 <= 25 Lacs"),
                    ("35", "> 25 Lacs < = 1 Crore"),
                    ("36", "Above 1 Crore"),
                ],
                default=33,
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
