# Generated by Django 5.0.6 on 2024-07-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0017_kycdetail_income_slab"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="created",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="transaction",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
