# Generated by Django 5.0.6 on 2024-07-30 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0019_alter_transaction_transaction_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="sip_dates",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="sip_num_inst",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="sip_num_inst_done",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="sip_order_ids",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="sip_start_date",
        ),
    ]
