# Generated by Django 5.0.6 on 2024-07-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0020_remove_transaction_sip_dates_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="id_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
