# Generated by Django 5.0.6 on 2024-07-30 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0021_transaction_id_deleted"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="id_deleted",
            new_name="is_deleted",
        ),
    ]
