# Generated by Django 5.0.6 on 2024-08-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0022_rename_id_deleted_transaction_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kycdetail",
            name="occ_code",
            field=models.CharField(
                blank=True, choices=[("02", "Services")], default="02", max_length=2
            ),
        ),
    ]
