# Generated by Django 5.0.6 on 2024-10-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0024_bserequest_kfintechportfolio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="kycdetail",
            name="citizen_type",
            field=models.CharField(
                blank=True,
                choices=[("RI", "Resident Indian"), ("NRI", "Non-Resident Indian")],
                max_length=10,
            ),
        ),
    ]
