# Generated by Django 5.0.6 on 2024-10-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0025_kycdetail_citizen_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="SIPScheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amc_code", models.CharField(max_length=100)),
                ("amc_name", models.CharField(max_length=255)),
                ("scheme_code", models.CharField(max_length=100)),
                ("scheme_name", models.CharField(max_length=255)),
                ("sip_transaction_mode", models.CharField(max_length=50)),
                ("sip_frequency", models.CharField(max_length=50)),
                ("sip_dates", models.CharField(max_length=255)),
                ("sip_minimum_gap", models.IntegerField()),
                ("sip_maximum_gap", models.IntegerField()),
                ("sip_installment_gap", models.IntegerField()),
                ("sip_status", models.CharField(max_length=50)),
                (
                    "sip_minimum_installment_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "sip_maximum_installment_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "sip_multiplier_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("sip_minimum_installment_numbers", models.IntegerField()),
                (
                    "sip_maximum_installment_numbers",
                    models.IntegerField(blank=True, null=True),
                ),
                ("scheme_isin", models.CharField(max_length=50)),
                ("scheme_type", models.CharField(max_length=50)),
                ("pause_flag", models.CharField(max_length=1)),
                (
                    "pause_minimum_installments",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "pause_maximum_installments",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "pause_modification_count",
                    models.IntegerField(blank=True, null=True),
                ),
                ("filler_1", models.CharField(blank=True, max_length=255, null=True)),
                ("filler_2", models.CharField(blank=True, max_length=255, null=True)),
                ("filler_3", models.CharField(blank=True, max_length=255, null=True)),
                ("filler_4", models.CharField(blank=True, max_length=255, null=True)),
                ("filler_5", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
