# Generated by Django 5.0.6 on 2024-10-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0026_sipscheme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sipscheme",
            name="amc_code",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="sipscheme",
            name="amc_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="sipscheme",
            name="filler_1",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="sipscheme",
            name="filler_2",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="sipscheme",
            name="filler_3",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="sipscheme",
            name="filler_4",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="sipscheme",
            name="filler_5",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="sipscheme",
            name="pause_flag",
            field=models.CharField(default="", max_length=1),
        ),
        migrations.AlterField(
            model_name="sipscheme",
            name="pause_maximum_installments",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="sipscheme",
            name="pause_minimum_installments",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="sipscheme",
            name="pause_modification_count",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="sipscheme",
            name="scheme_code",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="sipscheme",
            name="scheme_isin",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="sipscheme",
            name="scheme_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="sipscheme",
            name="scheme_type",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="sipscheme",
            name="sip_dates",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="sipscheme",
            name="sip_frequency",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="sipscheme",
            name="sip_installment_gap",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="sipscheme",
            name="sip_maximum_gap",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="sipscheme",
            name="sip_maximum_installment_amount",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="sipscheme",
            name="sip_maximum_installment_numbers",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="sipscheme",
            name="sip_minimum_gap",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="sipscheme",
            name="sip_minimum_installment_amount",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="sipscheme",
            name="sip_minimum_installment_numbers",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="sipscheme",
            name="sip_multiplier_amount",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="sipscheme",
            name="sip_status",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="sipscheme",
            name="sip_transaction_mode",
            field=models.CharField(default="", max_length=50),
        ),
    ]
